### ISSUE TITLE
How to compile and upload firmware for AstroTracker V0.6 REV2 (MiniTracker)

### ISSUE THREAD

**Issue by Joaliasbarb** [valcesch/AstroTracker#1]
Hello,

We are trying to compile and flash the firmware on a MiniTracker harwdare using Arduino IDE.
Unfortunately, the board description files for this hardware is not included in the repo and we didn't managed to create them. We're left with a lot of questions on how to proceed.

Could you provide us with some guidance on the necessary steps to perform ?

Cheers !

**Comment by valcesch** [comment]
Hello Joaliasbarb, 

When using the Arduino IDE, you need to select the Adafruit Feather M0 board (follow the procedure [here](https://learn.adafruit.com/adafruit-feather-m0-basic-proto/using-with-arduino-ide) to install the library) . 

You will probably have to burn the bootloader for this platform. Normally you can do it with the "Burn bootloader" tool in the Arduino IDE. There is also another procedure using Atmel Studio [here](https://learn.adafruit.com/how-to-program-samd-bootloaders/overview).

Hope this will solve your issue !
